apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hook-example
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pedro-cs-ribeiro/example-argo-app.git
    targetRevision: HEAD
    path: hook-test
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true